name: Run API Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Compilar con Maven
        run: mvn compile

      - name: Ejecutar pruebas con Maven
        run: ./mvnw clean test

      - name: Archiva resultados de test
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: target/test-results

      - name: Archiva screenshots si falla un test
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: screenshots
          path: target/screenshot-results

      - name: Carga Allure Report 
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-reports
          path: target/allure-results
